# Generated by Django 5.0.2 on 2024-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipe", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("image", models.ImageField(upload_to="receipe")),
            ],
        ),
    ]
